// Code generated by entc, DO NOT EDIT.

package course

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team19/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CourseName applies equality check predicate on the "Course_name" field. It's identical to CourseNameEQ.
func CourseName(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCourseName), v))
	})
}

// CourseNameEQ applies the EQ predicate on the "Course_name" field.
func CourseNameEQ(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCourseName), v))
	})
}

// CourseNameNEQ applies the NEQ predicate on the "Course_name" field.
func CourseNameNEQ(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCourseName), v))
	})
}

// CourseNameIn applies the In predicate on the "Course_name" field.
func CourseNameIn(vs ...string) predicate.Course {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Course(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCourseName), v...))
	})
}

// CourseNameNotIn applies the NotIn predicate on the "Course_name" field.
func CourseNameNotIn(vs ...string) predicate.Course {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Course(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCourseName), v...))
	})
}

// CourseNameGT applies the GT predicate on the "Course_name" field.
func CourseNameGT(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCourseName), v))
	})
}

// CourseNameGTE applies the GTE predicate on the "Course_name" field.
func CourseNameGTE(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCourseName), v))
	})
}

// CourseNameLT applies the LT predicate on the "Course_name" field.
func CourseNameLT(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCourseName), v))
	})
}

// CourseNameLTE applies the LTE predicate on the "Course_name" field.
func CourseNameLTE(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCourseName), v))
	})
}

// CourseNameContains applies the Contains predicate on the "Course_name" field.
func CourseNameContains(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCourseName), v))
	})
}

// CourseNameHasPrefix applies the HasPrefix predicate on the "Course_name" field.
func CourseNameHasPrefix(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCourseName), v))
	})
}

// CourseNameHasSuffix applies the HasSuffix predicate on the "Course_name" field.
func CourseNameHasSuffix(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCourseName), v))
	})
}

// CourseNameEqualFold applies the EqualFold predicate on the "Course_name" field.
func CourseNameEqualFold(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCourseName), v))
	})
}

// CourseNameContainsFold applies the ContainsFold predicate on the "Course_name" field.
func CourseNameContainsFold(v string) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCourseName), v))
	})
}

// HasInstructorInfoID applies the HasEdge predicate on the "InstructorInfo_id" edge.
func HasInstructorInfoID() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InstructorInfoIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InstructorInfoIDTable, InstructorInfoIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstructorInfoIDWith applies the HasEdge predicate on the "InstructorInfo_id" edge with a given conditions (other predicates).
func HasInstructorInfoIDWith(preds ...predicate.InstructorInfo) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(InstructorInfoIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InstructorInfoIDTable, InstructorInfoIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDepartmentID applies the HasEdge predicate on the "Department_id" edge.
func HasDepartmentID() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentIDTable, DepartmentIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDepartmentIDWith applies the HasEdge predicate on the "Department_id" edge with a given conditions (other predicates).
func HasDepartmentIDWith(preds ...predicate.Department) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DepartmentIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DepartmentIDTable, DepartmentIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDegreeID applies the HasEdge predicate on the "Degree_id" edge.
func HasDegreeID() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DegreeIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DegreeIDTable, DegreeIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDegreeIDWith applies the HasEdge predicate on the "Degree_id" edge with a given conditions (other predicates).
func HasDegreeIDWith(preds ...predicate.Degree) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DegreeIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DegreeIDTable, DegreeIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubjectID applies the HasEdge predicate on the "Subject_id" edge.
func HasSubjectID() predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SubjectIDTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubjectIDTable, SubjectIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubjectIDWith applies the HasEdge predicate on the "Subject_id" edge with a given conditions (other predicates).
func HasSubjectIDWith(preds ...predicate.Subject) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SubjectIDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubjectIDTable, SubjectIDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Course) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Course) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Course) predicate.Course {
	return predicate.Course(func(s *sql.Selector) {
		p(s.Not())
	})
}
