// Code generated by entc, DO NOT EDIT.

package subject

const (
	// Label holds the string label denoting the subject type in the database.
	Label = "subject"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubjectName holds the string denoting the subject_name field in the database.
	FieldSubjectName = "subject_name"

	// EdgeSubject holds the string denoting the subject edge name in mutations.
	EdgeSubject = "subject"

	// Table holds the table name of the subject in the database.
	Table = "subjects"
	// SubjectTable is the table the holds the subject relation/edge.
	SubjectTable = "courses"
	// SubjectInverseTable is the table name for the Course entity.
	// It exists in this package in order to avoid circular dependency with the "course" package.
	SubjectInverseTable = "courses"
	// SubjectColumn is the table column denoting the subject relation/edge.
	SubjectColumn = "Subject_id"
)

// Columns holds all SQL columns for subject fields.
var Columns = []string{
	FieldID,
	FieldSubjectName,
}
