// Code generated by entc, DO NOT EDIT.

package year

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team19/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// YEAR applies equality check predicate on the "YEAR" field. It's identical to YEAREQ.
func YEAR(v int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYEAR), v))
	})
}

// YEAREQ applies the EQ predicate on the "YEAR" field.
func YEAREQ(v int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldYEAR), v))
	})
}

// YEARNEQ applies the NEQ predicate on the "YEAR" field.
func YEARNEQ(v int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldYEAR), v))
	})
}

// YEARIn applies the In predicate on the "YEAR" field.
func YEARIn(vs ...int) predicate.Year {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Year(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldYEAR), v...))
	})
}

// YEARNotIn applies the NotIn predicate on the "YEAR" field.
func YEARNotIn(vs ...int) predicate.Year {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Year(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldYEAR), v...))
	})
}

// YEARGT applies the GT predicate on the "YEAR" field.
func YEARGT(v int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldYEAR), v))
	})
}

// YEARGTE applies the GTE predicate on the "YEAR" field.
func YEARGTE(v int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldYEAR), v))
	})
}

// YEARLT applies the LT predicate on the "YEAR" field.
func YEARLT(v int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldYEAR), v))
	})
}

// YEARLTE applies the LTE predicate on the "YEAR" field.
func YEARLTE(v int) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldYEAR), v))
	})
}

// HasSubjectsOffered applies the HasEdge predicate on the "SubjectsOffered" edge.
func HasSubjectsOffered() predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SubjectsOfferedTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubjectsOfferedTable, SubjectsOfferedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubjectsOfferedWith applies the HasEdge predicate on the "SubjectsOffered" edge with a given conditions (other predicates).
func HasSubjectsOfferedWith(preds ...predicate.SubjectsOffered) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SubjectsOfferedInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubjectsOfferedTable, SubjectsOfferedColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Year) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Year) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Year) predicate.Year {
	return predicate.Year(func(s *sql.Selector) {
		p(s.Not())
	})
}
