// Code generated by entc, DO NOT EDIT.

package instructorroom

const (
	// Label holds the string label denoting the instructorroom type in the database.
	Label = "instructor_room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldROOM holds the string denoting the room field in the database.
	FieldROOM = "room"
	// FieldBUILDING holds the string denoting the building field in the database.
	FieldBUILDING = "building"

	// EdgeInstructorinfos holds the string denoting the instructorinfos edge name in mutations.
	EdgeInstructorinfos = "instructorinfos"

	// Table holds the table name of the instructorroom in the database.
	Table = "instructor_rooms"
	// InstructorinfosTable is the table the holds the instructorinfos relation/edge.
	InstructorinfosTable = "instructor_infos"
	// InstructorinfosInverseTable is the table name for the InstructorInfo entity.
	// It exists in this package in order to avoid circular dependency with the "instructorinfo" package.
	InstructorinfosInverseTable = "instructor_infos"
	// InstructorinfosColumn is the table column denoting the instructorinfos relation/edge.
	InstructorinfosColumn = "instructorroom_id"
)

// Columns holds all SQL columns for instructorroom fields.
var Columns = []string{
	FieldID,
	FieldROOM,
	FieldBUILDING,
}
