// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/team19/app/ent/classroom"
)

// Classroom is the model entity for the Classroom schema.
type Classroom struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ROOM holds the value of the "ROOM" field.
	ROOM string `json:"ROOM,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClassroomQuery when eager-loading is set.
	Edges ClassroomEdges `json:"edges"`
}

// ClassroomEdges holds the relations/edges for other nodes in the graph.
type ClassroomEdges struct {
	// Courseclasses holds the value of the courseclasses edge.
	Courseclasses []*Courseclass
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CourseclassesOrErr returns the Courseclasses value or an error if the edge
// was not loaded in eager-loading.
func (e ClassroomEdges) CourseclassesOrErr() ([]*Courseclass, error) {
	if e.loadedTypes[0] {
		return e.Courseclasses, nil
	}
	return nil, &NotLoadedError{edge: "courseclasses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Classroom) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // ROOM
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Classroom fields.
func (c *Classroom) assignValues(values ...interface{}) error {
	if m, n := len(values), len(classroom.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	c.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field ROOM", values[0])
	} else if value.Valid {
		c.ROOM = value.String
	}
	return nil
}

// QueryCourseclasses queries the courseclasses edge of the Classroom.
func (c *Classroom) QueryCourseclasses() *CourseclassQuery {
	return (&ClassroomClient{config: c.config}).QueryCourseclasses(c)
}

// Update returns a builder for updating this Classroom.
// Note that, you need to call Classroom.Unwrap() before calling this method, if this Classroom
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Classroom) Update() *ClassroomUpdateOne {
	return (&ClassroomClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (c *Classroom) Unwrap() *Classroom {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Classroom is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Classroom) String() string {
	var builder strings.Builder
	builder.WriteString("Classroom(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", ROOM=")
	builder.WriteString(c.ROOM)
	builder.WriteByte(')')
	return builder.String()
}

// Classrooms is a parsable slice of Classroom.
type Classrooms []*Classroom

func (c Classrooms) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
