// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/team19/app/ent/classtime"
)

// Classtime is the model entity for the Classtime schema.
type Classtime struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TIME holds the value of the "TIME" field.
	TIME string `json:"TIME,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClasstimeQuery when eager-loading is set.
	Edges ClasstimeEdges `json:"edges"`
}

// ClasstimeEdges holds the relations/edges for other nodes in the graph.
type ClasstimeEdges struct {
	// Courseclasses holds the value of the courseclasses edge.
	Courseclasses []*Courseclass
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CourseclassesOrErr returns the Courseclasses value or an error if the edge
// was not loaded in eager-loading.
func (e ClasstimeEdges) CourseclassesOrErr() ([]*Courseclass, error) {
	if e.loadedTypes[0] {
		return e.Courseclasses, nil
	}
	return nil, &NotLoadedError{edge: "courseclasses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Classtime) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // TIME
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Classtime fields.
func (c *Classtime) assignValues(values ...interface{}) error {
	if m, n := len(values), len(classtime.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	c.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field TIME", values[0])
	} else if value.Valid {
		c.TIME = value.String
	}
	return nil
}

// QueryCourseclasses queries the courseclasses edge of the Classtime.
func (c *Classtime) QueryCourseclasses() *CourseclassQuery {
	return (&ClasstimeClient{config: c.config}).QueryCourseclasses(c)
}

// Update returns a builder for updating this Classtime.
// Note that, you need to call Classtime.Unwrap() before calling this method, if this Classtime
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Classtime) Update() *ClasstimeUpdateOne {
	return (&ClasstimeClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (c *Classtime) Unwrap() *Classtime {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Classtime is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Classtime) String() string {
	var builder strings.Builder
	builder.WriteString("Classtime(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", TIME=")
	builder.WriteString(c.TIME)
	builder.WriteByte(')')
	return builder.String()
}

// Classtimes is a parsable slice of Classtime.
type Classtimes []*Classtime

func (c Classtimes) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
