// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team19/app/ent/instructorinfo"
	"github.com/team19/app/ent/predicate"
)

// InstructorInfoDelete is the builder for deleting a InstructorInfo entity.
type InstructorInfoDelete struct {
	config
	hooks      []Hook
	mutation   *InstructorInfoMutation
	predicates []predicate.InstructorInfo
}

// Where adds a new predicate to the delete builder.
func (iid *InstructorInfoDelete) Where(ps ...predicate.InstructorInfo) *InstructorInfoDelete {
	iid.predicates = append(iid.predicates, ps...)
	return iid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iid *InstructorInfoDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iid.hooks) == 0 {
		affected, err = iid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InstructorInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iid.mutation = mutation
			affected, err = iid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iid.hooks) - 1; i >= 0; i-- {
			mut = iid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (iid *InstructorInfoDelete) ExecX(ctx context.Context) int {
	n, err := iid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iid *InstructorInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: instructorinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: instructorinfo.FieldID,
			},
		},
	}
	if ps := iid.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, iid.driver, _spec)
}

// InstructorInfoDeleteOne is the builder for deleting a single InstructorInfo entity.
type InstructorInfoDeleteOne struct {
	iid *InstructorInfoDelete
}

// Exec executes the deletion query.
func (iido *InstructorInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := iido.iid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{instructorinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iido *InstructorInfoDeleteOne) ExecX(ctx context.Context) {
	iido.iid.ExecX(ctx)
}
