// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team19/app/ent/instructorinfo"
	"github.com/team19/app/ent/instructorroom"
	"github.com/team19/app/ent/predicate"
)

// InstructorRoomQuery is the builder for querying InstructorRoom entities.
type InstructorRoomQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.InstructorRoom
	// eager-loading edges.
	withInstructorinfos *InstructorInfoQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (irq *InstructorRoomQuery) Where(ps ...predicate.InstructorRoom) *InstructorRoomQuery {
	irq.predicates = append(irq.predicates, ps...)
	return irq
}

// Limit adds a limit step to the query.
func (irq *InstructorRoomQuery) Limit(limit int) *InstructorRoomQuery {
	irq.limit = &limit
	return irq
}

// Offset adds an offset step to the query.
func (irq *InstructorRoomQuery) Offset(offset int) *InstructorRoomQuery {
	irq.offset = &offset
	return irq
}

// Order adds an order step to the query.
func (irq *InstructorRoomQuery) Order(o ...OrderFunc) *InstructorRoomQuery {
	irq.order = append(irq.order, o...)
	return irq
}

// QueryInstructorinfos chains the current query on the instructorinfos edge.
func (irq *InstructorRoomQuery) QueryInstructorinfos() *InstructorInfoQuery {
	query := &InstructorInfoQuery{config: irq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := irq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instructorroom.Table, instructorroom.FieldID, irq.sqlQuery()),
			sqlgraph.To(instructorinfo.Table, instructorinfo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, instructorroom.InstructorinfosTable, instructorroom.InstructorinfosColumn),
		)
		fromU = sqlgraph.SetNeighbors(irq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InstructorRoom entity in the query. Returns *NotFoundError when no instructorroom was found.
func (irq *InstructorRoomQuery) First(ctx context.Context) (*InstructorRoom, error) {
	irs, err := irq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(irs) == 0 {
		return nil, &NotFoundError{instructorroom.Label}
	}
	return irs[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (irq *InstructorRoomQuery) FirstX(ctx context.Context) *InstructorRoom {
	ir, err := irq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ir
}

// FirstID returns the first InstructorRoom id in the query. Returns *NotFoundError when no id was found.
func (irq *InstructorRoomQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = irq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{instructorroom.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (irq *InstructorRoomQuery) FirstXID(ctx context.Context) int {
	id, err := irq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only InstructorRoom entity in the query, returns an error if not exactly one entity was returned.
func (irq *InstructorRoomQuery) Only(ctx context.Context) (*InstructorRoom, error) {
	irs, err := irq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(irs) {
	case 1:
		return irs[0], nil
	case 0:
		return nil, &NotFoundError{instructorroom.Label}
	default:
		return nil, &NotSingularError{instructorroom.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (irq *InstructorRoomQuery) OnlyX(ctx context.Context) *InstructorRoom {
	ir, err := irq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ir
}

// OnlyID returns the only InstructorRoom id in the query, returns an error if not exactly one id was returned.
func (irq *InstructorRoomQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = irq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = &NotSingularError{instructorroom.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (irq *InstructorRoomQuery) OnlyIDX(ctx context.Context) int {
	id, err := irq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InstructorRooms.
func (irq *InstructorRoomQuery) All(ctx context.Context) ([]*InstructorRoom, error) {
	if err := irq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return irq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (irq *InstructorRoomQuery) AllX(ctx context.Context) []*InstructorRoom {
	irs, err := irq.All(ctx)
	if err != nil {
		panic(err)
	}
	return irs
}

// IDs executes the query and returns a list of InstructorRoom ids.
func (irq *InstructorRoomQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := irq.Select(instructorroom.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (irq *InstructorRoomQuery) IDsX(ctx context.Context) []int {
	ids, err := irq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (irq *InstructorRoomQuery) Count(ctx context.Context) (int, error) {
	if err := irq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return irq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (irq *InstructorRoomQuery) CountX(ctx context.Context) int {
	count, err := irq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (irq *InstructorRoomQuery) Exist(ctx context.Context) (bool, error) {
	if err := irq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return irq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (irq *InstructorRoomQuery) ExistX(ctx context.Context) bool {
	exist, err := irq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (irq *InstructorRoomQuery) Clone() *InstructorRoomQuery {
	return &InstructorRoomQuery{
		config:     irq.config,
		limit:      irq.limit,
		offset:     irq.offset,
		order:      append([]OrderFunc{}, irq.order...),
		unique:     append([]string{}, irq.unique...),
		predicates: append([]predicate.InstructorRoom{}, irq.predicates...),
		// clone intermediate query.
		sql:  irq.sql.Clone(),
		path: irq.path,
	}
}

//  WithInstructorinfos tells the query-builder to eager-loads the nodes that are connected to
// the "instructorinfos" edge. The optional arguments used to configure the query builder of the edge.
func (irq *InstructorRoomQuery) WithInstructorinfos(opts ...func(*InstructorInfoQuery)) *InstructorRoomQuery {
	query := &InstructorInfoQuery{config: irq.config}
	for _, opt := range opts {
		opt(query)
	}
	irq.withInstructorinfos = query
	return irq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ROOM string `json:"ROOM,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InstructorRoom.Query().
//		GroupBy(instructorroom.FieldROOM).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (irq *InstructorRoomQuery) GroupBy(field string, fields ...string) *InstructorRoomGroupBy {
	group := &InstructorRoomGroupBy{config: irq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := irq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return irq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		ROOM string `json:"ROOM,omitempty"`
//	}
//
//	client.InstructorRoom.Query().
//		Select(instructorroom.FieldROOM).
//		Scan(ctx, &v)
//
func (irq *InstructorRoomQuery) Select(field string, fields ...string) *InstructorRoomSelect {
	selector := &InstructorRoomSelect{config: irq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := irq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return irq.sqlQuery(), nil
	}
	return selector
}

func (irq *InstructorRoomQuery) prepareQuery(ctx context.Context) error {
	if irq.path != nil {
		prev, err := irq.path(ctx)
		if err != nil {
			return err
		}
		irq.sql = prev
	}
	return nil
}

func (irq *InstructorRoomQuery) sqlAll(ctx context.Context) ([]*InstructorRoom, error) {
	var (
		nodes       = []*InstructorRoom{}
		_spec       = irq.querySpec()
		loadedTypes = [1]bool{
			irq.withInstructorinfos != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &InstructorRoom{config: irq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, irq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := irq.withInstructorinfos; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*InstructorRoom)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.InstructorInfo(func(s *sql.Selector) {
			s.Where(sql.InValues(instructorroom.InstructorinfosColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.instructorroom_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "instructorroom_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "instructorroom_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Instructorinfos = append(node.Edges.Instructorinfos, n)
		}
	}

	return nodes, nil
}

func (irq *InstructorRoomQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := irq.querySpec()
	return sqlgraph.CountNodes(ctx, irq.driver, _spec)
}

func (irq *InstructorRoomQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := irq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (irq *InstructorRoomQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   instructorroom.Table,
			Columns: instructorroom.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: instructorroom.FieldID,
			},
		},
		From:   irq.sql,
		Unique: true,
	}
	if ps := irq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := irq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := irq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := irq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (irq *InstructorRoomQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(irq.driver.Dialect())
	t1 := builder.Table(instructorroom.Table)
	selector := builder.Select(t1.Columns(instructorroom.Columns...)...).From(t1)
	if irq.sql != nil {
		selector = irq.sql
		selector.Select(selector.Columns(instructorroom.Columns...)...)
	}
	for _, p := range irq.predicates {
		p(selector)
	}
	for _, p := range irq.order {
		p(selector)
	}
	if offset := irq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := irq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InstructorRoomGroupBy is the builder for group-by InstructorRoom entities.
type InstructorRoomGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (irgb *InstructorRoomGroupBy) Aggregate(fns ...AggregateFunc) *InstructorRoomGroupBy {
	irgb.fns = append(irgb.fns, fns...)
	return irgb
}

// Scan applies the group-by query and scan the result into the given value.
func (irgb *InstructorRoomGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := irgb.path(ctx)
	if err != nil {
		return err
	}
	irgb.sql = query
	return irgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := irgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) StringsX(ctx context.Context) []string {
	v, err := irgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = irgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) StringX(ctx context.Context) string {
	v, err := irgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) IntsX(ctx context.Context) []int {
	v, err := irgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = irgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) IntX(ctx context.Context) int {
	v, err := irgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := irgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = irgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) Float64X(ctx context.Context) float64 {
	v, err := irgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := irgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (irgb *InstructorRoomGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = irgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (irgb *InstructorRoomGroupBy) BoolX(ctx context.Context) bool {
	v, err := irgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (irgb *InstructorRoomGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := irgb.sqlQuery().Query()
	if err := irgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (irgb *InstructorRoomGroupBy) sqlQuery() *sql.Selector {
	selector := irgb.sql
	columns := make([]string, 0, len(irgb.fields)+len(irgb.fns))
	columns = append(columns, irgb.fields...)
	for _, fn := range irgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(irgb.fields...)
}

// InstructorRoomSelect is the builder for select fields of InstructorRoom entities.
type InstructorRoomSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (irs *InstructorRoomSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := irs.path(ctx)
	if err != nil {
		return err
	}
	irs.sql = query
	return irs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (irs *InstructorRoomSelect) ScanX(ctx context.Context, v interface{}) {
	if err := irs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) Strings(ctx context.Context) ([]string, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (irs *InstructorRoomSelect) StringsX(ctx context.Context) []string {
	v, err := irs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = irs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (irs *InstructorRoomSelect) StringX(ctx context.Context) string {
	v, err := irs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) Ints(ctx context.Context) ([]int, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (irs *InstructorRoomSelect) IntsX(ctx context.Context) []int {
	v, err := irs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = irs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (irs *InstructorRoomSelect) IntX(ctx context.Context) int {
	v, err := irs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (irs *InstructorRoomSelect) Float64sX(ctx context.Context) []float64 {
	v, err := irs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = irs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (irs *InstructorRoomSelect) Float64X(ctx context.Context) float64 {
	v, err := irs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: InstructorRoomSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (irs *InstructorRoomSelect) BoolsX(ctx context.Context) []bool {
	v, err := irs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (irs *InstructorRoomSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = irs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{instructorroom.Label}
	default:
		err = fmt.Errorf("ent: InstructorRoomSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (irs *InstructorRoomSelect) BoolX(ctx context.Context) bool {
	v, err := irs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (irs *InstructorRoomSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := irs.sqlQuery().Query()
	if err := irs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (irs *InstructorRoomSelect) sqlQuery() sql.Querier {
	selector := irs.sql
	selector.Select(selector.Columns(irs.fields...)...)
	return selector
}
