// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team19/app/ent/instructorroom"
	"github.com/team19/app/ent/predicate"
)

// InstructorRoomDelete is the builder for deleting a InstructorRoom entity.
type InstructorRoomDelete struct {
	config
	hooks      []Hook
	mutation   *InstructorRoomMutation
	predicates []predicate.InstructorRoom
}

// Where adds a new predicate to the delete builder.
func (ird *InstructorRoomDelete) Where(ps ...predicate.InstructorRoom) *InstructorRoomDelete {
	ird.predicates = append(ird.predicates, ps...)
	return ird
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ird *InstructorRoomDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ird.hooks) == 0 {
		affected, err = ird.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InstructorRoomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ird.mutation = mutation
			affected, err = ird.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ird.hooks) - 1; i >= 0; i-- {
			mut = ird.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ird.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ird *InstructorRoomDelete) ExecX(ctx context.Context) int {
	n, err := ird.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ird *InstructorRoomDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: instructorroom.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: instructorroom.FieldID,
			},
		},
	}
	if ps := ird.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ird.driver, _spec)
}

// InstructorRoomDeleteOne is the builder for deleting a single InstructorRoom entity.
type InstructorRoomDeleteOne struct {
	ird *InstructorRoomDelete
}

// Exec executes the deletion query.
func (irdo *InstructorRoomDeleteOne) Exec(ctx context.Context) error {
	n, err := irdo.ird.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{instructorroom.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (irdo *InstructorRoomDeleteOne) ExecX(ctx context.Context) {
	irdo.ird.ExecX(ctx)
}
