// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team19/app/ent/subjectsoffered"
	"github.com/team19/app/ent/year"
)

// YearCreate is the builder for creating a Year entity.
type YearCreate struct {
	config
	mutation *YearMutation
	hooks    []Hook
}

// SetYEAR sets the YEAR field.
func (yc *YearCreate) SetYEAR(i int) *YearCreate {
	yc.mutation.SetYEAR(i)
	return yc
}

// AddSubjectsOfferedIDs adds the SubjectsOffered edge to SubjectsOffered by ids.
func (yc *YearCreate) AddSubjectsOfferedIDs(ids ...int) *YearCreate {
	yc.mutation.AddSubjectsOfferedIDs(ids...)
	return yc
}

// AddSubjectsOffered adds the SubjectsOffered edges to SubjectsOffered.
func (yc *YearCreate) AddSubjectsOffered(s ...*SubjectsOffered) *YearCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return yc.AddSubjectsOfferedIDs(ids...)
}

// Mutation returns the YearMutation object of the builder.
func (yc *YearCreate) Mutation() *YearMutation {
	return yc.mutation
}

// Save creates the Year in the database.
func (yc *YearCreate) Save(ctx context.Context) (*Year, error) {
	if _, ok := yc.mutation.YEAR(); !ok {
		return nil, &ValidationError{Name: "YEAR", err: errors.New("ent: missing required field \"YEAR\"")}
	}
	var (
		err  error
		node *Year
	)
	if len(yc.hooks) == 0 {
		node, err = yc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*YearMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			yc.mutation = mutation
			node, err = yc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(yc.hooks) - 1; i >= 0; i-- {
			mut = yc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, yc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (yc *YearCreate) SaveX(ctx context.Context) *Year {
	v, err := yc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (yc *YearCreate) sqlSave(ctx context.Context) (*Year, error) {
	y, _spec := yc.createSpec()
	if err := sqlgraph.CreateNode(ctx, yc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	y.ID = int(id)
	return y, nil
}

func (yc *YearCreate) createSpec() (*Year, *sqlgraph.CreateSpec) {
	var (
		y     = &Year{config: yc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: year.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: year.FieldID,
			},
		}
	)
	if value, ok := yc.mutation.YEAR(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: year.FieldYEAR,
		})
		y.YEAR = value
	}
	if nodes := yc.mutation.SubjectsOfferedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   year.SubjectsOfferedTable,
			Columns: []string{year.SubjectsOfferedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: subjectsoffered.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return y, _spec
}
