// Code generated by entc, DO NOT EDIT.

package degree

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team19/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// DegreeName applies equality check predicate on the "Degree_name" field. It's identical to DegreeNameEQ.
func DegreeName(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDegreeName), v))
	})
}

// DegreeNameEQ applies the EQ predicate on the "Degree_name" field.
func DegreeNameEQ(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDegreeName), v))
	})
}

// DegreeNameNEQ applies the NEQ predicate on the "Degree_name" field.
func DegreeNameNEQ(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDegreeName), v))
	})
}

// DegreeNameIn applies the In predicate on the "Degree_name" field.
func DegreeNameIn(vs ...string) predicate.Degree {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Degree(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDegreeName), v...))
	})
}

// DegreeNameNotIn applies the NotIn predicate on the "Degree_name" field.
func DegreeNameNotIn(vs ...string) predicate.Degree {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Degree(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDegreeName), v...))
	})
}

// DegreeNameGT applies the GT predicate on the "Degree_name" field.
func DegreeNameGT(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDegreeName), v))
	})
}

// DegreeNameGTE applies the GTE predicate on the "Degree_name" field.
func DegreeNameGTE(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDegreeName), v))
	})
}

// DegreeNameLT applies the LT predicate on the "Degree_name" field.
func DegreeNameLT(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDegreeName), v))
	})
}

// DegreeNameLTE applies the LTE predicate on the "Degree_name" field.
func DegreeNameLTE(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDegreeName), v))
	})
}

// DegreeNameContains applies the Contains predicate on the "Degree_name" field.
func DegreeNameContains(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDegreeName), v))
	})
}

// DegreeNameHasPrefix applies the HasPrefix predicate on the "Degree_name" field.
func DegreeNameHasPrefix(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDegreeName), v))
	})
}

// DegreeNameHasSuffix applies the HasSuffix predicate on the "Degree_name" field.
func DegreeNameHasSuffix(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDegreeName), v))
	})
}

// DegreeNameEqualFold applies the EqualFold predicate on the "Degree_name" field.
func DegreeNameEqualFold(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDegreeName), v))
	})
}

// DegreeNameContainsFold applies the ContainsFold predicate on the "Degree_name" field.
func DegreeNameContainsFold(v string) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDegreeName), v))
	})
}

// HasDegree applies the HasEdge predicate on the "degree" edge.
func HasDegree() predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DegreeTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DegreeTable, DegreeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDegreeWith applies the HasEdge predicate on the "degree" edge with a given conditions (other predicates).
func HasDegreeWith(preds ...predicate.Course) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DegreeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DegreeTable, DegreeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Degree) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Degree) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Degree) predicate.Degree {
	return predicate.Degree(func(s *sql.Selector) {
		p(s.Not())
	})
}
