/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntClasstimeEdges,
    EntClasstimeEdgesFromJSON,
    EntClasstimeEdgesFromJSONTyped,
    EntClasstimeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntClasstime
 */
export interface EntClasstime {
    /**
     * TIME holds the value of the "TIME" field.
     * @type {string}
     * @memberof EntClasstime
     */
    tIME?: string;
    /**
     * 
     * @type {EntClasstimeEdges}
     * @memberof EntClasstime
     */
    edges?: EntClasstimeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntClasstime
     */
    id?: number;
}

export function EntClasstimeFromJSON(json: any): EntClasstime {
    return EntClasstimeFromJSONTyped(json, false);
}

export function EntClasstimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntClasstime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tIME': !exists(json, 'TIME') ? undefined : json['TIME'],
        'edges': !exists(json, 'edges') ? undefined : EntClasstimeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntClasstimeToJSON(value?: EntClasstime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TIME': value.tIME,
        'edges': EntClasstimeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


