/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCourse,
    EntCourseFromJSON,
    EntCourseFromJSONTyped,
    EntCourseToJSON,
    EntInstructorInfo,
    EntInstructorInfoFromJSON,
    EntInstructorInfoFromJSONTyped,
    EntInstructorInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDepartmentEdges
 */
export interface EntDepartmentEdges {
    /**
     * Department holds the value of the department edge.
     * @type {Array<EntCourse>}
     * @memberof EntDepartmentEdges
     */
    department?: Array<EntCourse>;
    /**
     * Instructorinfos holds the value of the instructorinfos edge.
     * @type {Array<EntInstructorInfo>}
     * @memberof EntDepartmentEdges
     */
    instructorinfos?: Array<EntInstructorInfo>;
}

export function EntDepartmentEdgesFromJSON(json: any): EntDepartmentEdges {
    return EntDepartmentEdgesFromJSONTyped(json, false);
}

export function EntDepartmentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDepartmentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'department') ? undefined : ((json['department'] as Array<any>).map(EntCourseFromJSON)),
        'instructorinfos': !exists(json, 'instructorinfos') ? undefined : ((json['instructorinfos'] as Array<any>).map(EntInstructorInfoFromJSON)),
    };
}

export function EntDepartmentEdgesToJSON(value?: EntDepartmentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': value.department === undefined ? undefined : ((value.department as Array<any>).map(EntCourseToJSON)),
        'instructorinfos': value.instructorinfos === undefined ? undefined : ((value.instructorinfos as Array<any>).map(EntInstructorInfoToJSON)),
    };
}


