/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDepartmentEdges,
    EntDepartmentEdgesFromJSON,
    EntDepartmentEdgesFromJSONTyped,
    EntDepartmentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDepartment
 */
export interface EntDepartment {
    /**
     * DEPARTMENT holds the value of the "DEPARTMENT" field.
     * @type {string}
     * @memberof EntDepartment
     */
    dEPARTMENT?: string;
    /**
     * FACULTY holds the value of the "FACULTY" field.
     * @type {string}
     * @memberof EntDepartment
     */
    fACULTY?: string;
    /**
     * 
     * @type {EntDepartmentEdges}
     * @memberof EntDepartment
     */
    edges?: EntDepartmentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDepartment
     */
    id?: number;
}

export function EntDepartmentFromJSON(json: any): EntDepartment {
    return EntDepartmentFromJSONTyped(json, false);
}

export function EntDepartmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDepartment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dEPARTMENT': !exists(json, 'DEPARTMENT') ? undefined : json['DEPARTMENT'],
        'fACULTY': !exists(json, 'FACULTY') ? undefined : json['FACULTY'],
        'edges': !exists(json, 'edges') ? undefined : EntDepartmentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntDepartmentToJSON(value?: EntDepartment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DEPARTMENT': value.dEPARTMENT,
        'FACULTY': value.fACULTY,
        'edges': EntDepartmentEdgesToJSON(value.edges),
        'id': value.id,
    };
}


