/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDegreeEdges,
    EntDegreeEdgesFromJSON,
    EntDegreeEdgesFromJSONTyped,
    EntDegreeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDegree
 */
export interface EntDegree {
    /**
     * DegreeName holds the value of the "Degree_name" field.
     * @type {string}
     * @memberof EntDegree
     */
    degreeName?: string;
    /**
     * 
     * @type {EntDegreeEdges}
     * @memberof EntDegree
     */
    edges?: EntDegreeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDegree
     */
    id?: number;
}

export function EntDegreeFromJSON(json: any): EntDegree {
    return EntDegreeFromJSONTyped(json, false);
}

export function EntDegreeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDegree {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'degreeName': !exists(json, 'Degree_name') ? undefined : json['Degree_name'],
        'edges': !exists(json, 'edges') ? undefined : EntDegreeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntDegreeToJSON(value?: EntDegree | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Degree_name': value.degreeName,
        'edges': EntDegreeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


