/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntInstructorInfo,
    EntInstructorInfoFromJSON,
    EntInstructorInfoFromJSONTyped,
    EntInstructorInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTitleEdges
 */
export interface EntTitleEdges {
    /**
     * Instructorinfos holds the value of the instructorinfos edge.
     * @type {Array<EntInstructorInfo>}
     * @memberof EntTitleEdges
     */
    instructorinfos?: Array<EntInstructorInfo>;
}

export function EntTitleEdgesFromJSON(json: any): EntTitleEdges {
    return EntTitleEdgesFromJSONTyped(json, false);
}

export function EntTitleEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTitleEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instructorinfos': !exists(json, 'instructorinfos') ? undefined : ((json['instructorinfos'] as Array<any>).map(EntInstructorInfoFromJSON)),
    };
}

export function EntTitleEdgesToJSON(value?: EntTitleEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instructorinfos': value.instructorinfos === undefined ? undefined : ((value.instructorinfos as Array<any>).map(EntInstructorInfoToJSON)),
    };
}


