/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntYearEdges,
    EntYearEdgesFromJSON,
    EntYearEdgesFromJSONTyped,
    EntYearEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntYear
 */
export interface EntYear {
    /**
     * YEAR holds the value of the "YEAR" field.
     * @type {number}
     * @memberof EntYear
     */
    yEAR?: number;
    /**
     * 
     * @type {EntYearEdges}
     * @memberof EntYear
     */
    edges?: EntYearEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntYear
     */
    id?: number;
}

export function EntYearFromJSON(json: any): EntYear {
    return EntYearFromJSONTyped(json, false);
}

export function EntYearFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntYear {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'yEAR': !exists(json, 'YEAR') ? undefined : json['YEAR'],
        'edges': !exists(json, 'edges') ? undefined : EntYearEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntYearToJSON(value?: EntYear | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'YEAR': value.yEAR,
        'edges': EntYearEdgesToJSON(value.edges),
        'id': value.id,
    };
}


